# SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
# SPDX-License-Identifier: ISC

FROM debian:trixie-slim AS builder

    ARG DEBIAN_SNAPSHOT=20260227T000000Z

    # Freeze apt repository state to stabilize toolchain versions across CI runs.
    RUN rm -f /etc/apt/sources.list.d/debian.sources && \
        printf '%s\n' \
          "deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/${DEBIAN_SNAPSHOT} trixie main" \
          > /etc/apt/sources.list && \
        printf '%s\n' \
          "Acquire::Check-Valid-Until \"false\";" \
          > /etc/apt/apt.conf.d/99snapshot

    # Update distro
    RUN apt-get -y update

    # Copy contents
    COPY "build/" "/usr/src/shvr"
    COPY "checksums/" "/shvr/checksums"
    COPY "common/" "/shvr/common"
    COPY "patches/" "/shvr/patches"
    COPY "variants/" "/shvr/variants"

    COPY "shvr.sh" "/shvr/shvr.sh"
    RUN chmod +x "/shvr/shvr.sh"

    # Setup environment
    ENV SHVR_DIR_SRC="/usr/src/shvr"
    ENV SHVR_DIR_OUT="/opt"
    ARG TARGETS

    # Build
    RUN bash "/shvr/shvr.sh" deps $TARGETS
    RUN bash "/shvr/shvr.sh" build $TARGETS

    # Extract unique library dependencies
    RUN mkdir -p /deps/bin && \
        find /opt -type f -executable -exec ldd {} \; 2>/dev/null | \
        grep -o '/\(lib\|usr/lib\)[^ ]*\.so[^ ]*' | sort | uniq | \
        xargs -I {} cp --parents {} /deps/

    RUN mkdir -p /deps/opt/shvr && \
        find /opt \( -type l -o -type f \) | sort -t'_' -k1,1 -k2Vr > /deps/opt/shvr/manifest.txt && \
        { \
          echo "debian_snapshot=${DEBIAN_SNAPSHOT}"; \
          echo "dpkg_arch=$(dpkg --print-architecture 2>/dev/null || true)"; \
          echo "gcc_version=$(gcc --version 2>/dev/null | head -n1 || true)"; \
          echo "gcc12_version=$(gcc-12 --version 2>/dev/null | head -n1 || true)"; \
          echo "binutils_strip=$(strip --version 2>/dev/null | head -n1 || true)"; \
          echo "binutils_objcopy=$(objcopy --version 2>/dev/null | head -n1 || true)"; \
          echo "binutils_ar=$(ar --version 2>/dev/null | head -n1 || true)"; \
          echo "binutils_ld=$(ld --version 2>/dev/null | head -n1 || true)"; \
          echo "--- dpkg selected toolchain packages ---"; \
          dpkg-query -W 2>/dev/null | grep -E '^(binutils|gcc(|-[0-9]+)|g\\+\\+(|-[0-9]+)|libc6|make)[[:space:]]' | sort || true; \
        } > /deps/opt/shvr/toolchain.txt && \
        printf '%s\n' \
          "build-info.txt note: host-specific build metadata is generated by the CI action .github/actions/generate-build-checksums." \
          "This in-image file is intentionally static for reproducibility." \
          > /deps/opt/shvr/build-info.txt && \
        printf '%s\n' \
          "build-env.txt note: CI host environment details are captured by .github/actions/generate-build-checksums." \
          "This in-image file is intentionally static for reproducibility." \
          > /deps/opt/shvr/build-env.txt


FROM busybox:stable-musl

    # Copy helper script
    COPY "entrypoint.sh" "/opt/shvr/entrypoint.sh"

    # Setup environment
    ENV SHVR_DIR_OUT=/opt

    # Copy built artifacts with preserved metadata for reproducibility
    WORKDIR /
    COPY --from=builder --chown=0:0 "$SHVR_DIR_OUT" "$SHVR_DIR_OUT"
    COPY --from=builder --chown=0:0 /shvr/checksums/build /opt/shvr/checksums/build
    COPY --from=builder --chown=0:0 /deps /

    ENTRYPOINT [ "/bin/sh", "/opt/shvr/entrypoint.sh" ]
