#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
# SPDX-License-Identifier: ISC

shrun () {
    echo "# ${1#/opt/}"
    shift
    "${@:-}"
}

find /opt -type f | sort --version-sort | while read -r sh_path
do
    case $sh_path in
        *shcomp) continue ;;
        *busybox)
            shrun "$sh_path" "$sh_path" ash "$@"
            shrun "$sh_path" "$sh_path" hush "$@"
            ;;
        *) shrun "$sh_path" "$sh_path" "$@"
    esac
done