# SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
# SPDX-License-Identifier: ISC

name: Single Download
description: Download and cache a single shell source code
inputs:
  shvr_shell:
    description: 'Shell variant to download'
    required: true
  shvr_version:
    description: 'Shell version to download'
    required: true
  cache_path:
    description: 'Cache path to use'
    required: false
runs:
  using: composite
  steps:
    - uses: actions/cache/restore@v4
      id: restore-shell
      env:
        cache-name: cache-shell
      with:
        path: |
          build/${{ inputs.cache_path }}**
        key: build-${{ env.cache-name }}-${{ inputs.shvr_shell }}-${{ inputs.shvr_version }}
    - shell: sh
      run: sh shvr.sh download "${{ inputs.shvr_shell }}_${{ inputs.shvr_version }}"
    - uses: actions/cache/save@v4
      if: steps.restore-shell.outputs.cache-hit != 'true'
      id: cache-shell
      env:
        cache-name: cache-shell
      with:
        path: |
          build/${{ inputs.cache_path }}**
        key: build-${{ env.cache-name }}-${{ inputs.shvr_shell }}-${{ inputs.shvr_version }}
